objects/Account.object
<CustomObject>
    <fields>
        <fullName>HC_fld_cuentaBancaria__c</fullName>
        <description>Código de la cuenta bancaria (IBAN)</description>
        <label>Código de la cuenta bancaria (IBAN)</label>
        <length>24</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HC_fld_documentoIdentidad__c</fullName>
        <label>D.N.I</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HC_fld_estadoCivil__c</fullName>
        <description>Estado Civil: Soltero, Casado, Viudo, Divorciado</description>
        <label>Estado Civil</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Soltero</fullName>
                </value>
                <value>
                    <fullName>Casado</fullName>
                </value>
                <value>
                    <fullName>Viudo</fullName>
                </value>
                <value>
                    <fullName>Divorciado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_frecuenciaPago__c</fullName>
        <label>Frecuencia de Pago</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mensual</fullName>
                </value>
                <value>
                    <fullName>Trimestral</fullName>
                </value>
                <value>
                    <fullName>Semestral</fullName>
                </value>
                <value>
                    <fullName>Anual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_identificacionBanco__c</fullName>
        <description>Santander(BSCHESMMXXX), BBVA (BBVAESMMXXX), Caixa (CAIXESBBXXX), Sabadell(BSABESBBXXX), Bankinter(BKBKESMMXXX), Unicaja (UCJAES2MXXX)</description>
        <label>Código de identificación del banco (BIC)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Santander(BSCHESMMXXX)</fullName>
                </value>
                <value>
                    <fullName>BBVA (BBVAESMMXXX)</fullName>
                </value>
                <value>
                    <fullName>Caixa (CAIXESBBXXX)</fullName>
                </value>
                <value>
                    <fullName>Sabadell (BSABESBBXXX)</fullName>
                </value>
                <value>
                    <fullName>Bankinter (BKBKESMMXXX)</fullName>
                </value>
                <value>
                    <fullName>Unicaja (UCJAES2MXXX)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_preferenciasComunicacion__c</fullName>
        <label>Preferencias de Comunicación</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Teléfono</fullName>
                </value>
                <value>
                    <fullName>Correo Postal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_tipoPago__c</fullName>
        <description>Tipo de Pago: Orden de Domiciliación o No domiciliada</description>
        <label>Tipo Pago</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Orden de Domiciliación</fullName>
                </value>
                <value>
                    <fullName>No domiciliada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>HC_rt_miembroCompania</fullName>
        <active>true</active>
        <description>Record Type para identificar a los Account de Clientes de tipo B2C</description>
        <label>Miembro Compañía</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/AccountContactRelation.object
<CustomObject>
    <fields>
        <fullName>HC_fld_tipoContacto__c</fullName>
        <label>Tipo de Contacto</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Miembro de la familia</fullName>
                </value>
                <value>
                    <fullName>Contacto de emergencia</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HealthCloudGA__BirthDate__c</fullName>
        <formula>IF( NOT( ISBLANK( Birthdate ) ) , CASE(MONTH( Birthdate ),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;,
4, &quot;April&quot;,
5, &quot;May&quot;,
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;)+ &apos; &apos;+TEXT(DAY(Birthdate))+&apos;,&apos;+&apos; &apos;+TEXT(Year(Birthdate)), &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Birth Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HealthCloudGA__Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Decline to Specify</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>HC_rt_contactmiembroCompania</fullName>
        <active>true</active>
        <description>Record Type de contacto&apos;s relacionados con los miembros de la compañía.</description>
        <label>Contacto Miembro Compañía</label>
    </recordTypes>
    <recordTypes>
        <fullName>HC_rt_portalUser</fullName>
        <active>true</active>
        <description>Record Type para identificar los contactos pertenecientes al portal</description>
        <label>Portal User</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contract.object
<CustomObject>
    <recordTypes>
        <fullName>HC_rt_contratoSeguroCliente</fullName>
        <active>true</active>
        <description>Record Type que identifica los Contratos de los Miembros de la Compañia</description>
        <label>Contrato Seguro Cliente</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContractGroupPlan.object
<CustomObject>
    <recordTypes>
        <fullName>HC_rt_contratoSeguroCliente</fullName>
        <active>true</active>
        <description>Record Type para identificar la relación entre poliza y contrato del seguro del cliente</description>
        <label>Contrato Seguro Cliente</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CoverageBenefit.object
<CustomObject>
    <fields>
        <fullName>HC_fld_careProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo custom relacionado con Care Program</description>
        <label>Care Program</label>
        <referenceTo>CareProgram</referenceTo>
        <relationshipLabel>Coverage Benefits</relationshipLabel>
        <relationshipName>Coverage_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/HealthCondition.object
<CustomObject>
    <fields>
        <fullName>HC_fld_lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo que relaciona el cliente potencial con la condición de salud</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Health Conditions</relationshipLabel>
        <relationshipName>Health_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/InsurancePolicy.object
<CustomObject>
    <fields>
        <fullName>HC_fld_renovacionAutomatica__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Campo custom que marcá si la poliza se renueva automaticamente.</description>
        <label>Renovación Automática</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>HC_rt_polizaSeguros</fullName>
        <active>true</active>
        <description>Record Type para identidicar la Polizas de Seguro de los Clientes</description>
        <label>Póliza de Seguros</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/InsurancePolicyCoverage.object
<CustomObject>
    <recordTypes>
        <fullName>HC_rt_coverturaPolizaSeguros</fullName>
        <active>true</active>
        <description>Record Type usado para identificar la covertura del seguro de salud</description>
        <label>Cobertura Póliza de Seguros</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>HC_fld_cuentaBancaria__c</fullName>
        <description>Código de la cuenta bancaria (IBAN)</description>
        <label>Código de la cuenta bancaria (IBAN)</label>
        <length>24</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HC_fld_documentoIdentidad__c</fullName>
        <description>D.N.I</description>
        <label>D.N.I</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HC_fld_estadoCivil__c</fullName>
        <description>Estado Civil: Soltero, Casado, Viudo, Divorciado</description>
        <label>Estado Civil</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Soltero</fullName>
                </value>
                <value>
                    <fullName>Casado</fullName>
                </value>
                <value>
                    <fullName>Viudo</fullName>
                </value>
                <value>
                    <fullName>Divorciado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_frecuenciaPago__c</fullName>
        <description>Frecuencia de Pago</description>
        <label>Frecuencia de Pago</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mensual</fullName>
                </value>
                <value>
                    <fullName>Trimestral</fullName>
                </value>
                <value>
                    <fullName>Semestral</fullName>
                </value>
                <value>
                    <fullName>Anual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_identificacionBanco__c</fullName>
        <description>Santander(BSCHESMMXXX), BBVA (BBVAESMMXXX), Caixa (CAIXESBBXXX), Sabadell(BSABESBBXXX), Bankinter(BKBKESMMXXX), Unicaja (UCJAES2MXXX)</description>
        <label>Código de identificación del banco (BIC)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Santander(BSCHESMMXXX)</fullName>
                </value>
                <value>
                    <fullName>BBVA (BBVAESMMXXX)</fullName>
                </value>
                <value>
                    <fullName>Caixa (CAIXESBBXXX)</fullName>
                </value>
                <value>
                    <fullName>Sabadell (BSABESBBXXX)</fullName>
                </value>
                <value>
                    <fullName>Bankinter (BKBKESMMXXX)</fullName>
                </value>
                <value>
                    <fullName>Unicaja (UCJAES2MXXX)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_preferenciasComunicacion__c</fullName>
        <description>Preferencias de Comunicación</description>
        <label>Preferencias de Comunicación</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Teléfono</fullName>
                </value>
                <value>
                    <fullName>Correo Postal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_tipoPago__c</fullName>
        <description>Tipo de Pago: Orden de Domiciliación o No domiciliada</description>
        <label>Tipo Pago</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Orden de Domiciliación</fullName>
                </value>
                <value>
                    <fullName>No domiciliada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HealthCloudGA__BirthDate__c</fullName>
        <label>Birth Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HealthCloudGA__EmergencyContactFirstName__c</fullName>
        <label>Emergency Contact First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HealthCloudGA__EmergencyContactLastName__c</fullName>
        <label>Emergency Contact Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HealthCloudGA__EmergencyContactPhone__c</fullName>
        <label>Emergency Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>HealthCloudGA__Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HealthCloudGA__RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to the patient or member Account who is being referred.</description>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Related Account)</relationshipLabel>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>HC_rt_cPotencialMbrSeguro</fullName>
        <active>true</active>
        <businessProcess>HC_prcs_clientePotencialSeguros</businessProcess>
        <description>Record Type de clientes potenciales</description>
        <label>Cliente Potencial Miembro Seguro</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/HC_cls_handlerTriggerLead.cls
public without sharing class HC_cls_handlerTriggerLead {
    
    public static void afterUpdateContratoFirmado(List<Lead> listNew, Map<Id, Lead> newMap, List<Lead> oldList, Map<Id,Lead> oldMap) {
        
        if(!listNew.isEmpty()){
            for(Lead lead : listNew){
                Lead oldLead = oldMap.get(lead.id);
                if(lead.RecordTypeId == Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('HC_rt_cPotencialMbrSeguro').getRecordTypeId() && lead.Status == 'Contrato Firmado' && oldLead.Status != 'Contrato Firmado' ){
                    Account newAccount = new Account();
                    newAccount.ShippingCity = lead.City;
                    newAccount.AnnualRevenue = lead.AnnualRevenue;
                    newAccount.ShippingCountry = lead.Country;
                    newAccount.Description = lead.Description;
                    //newAccount.PersonEmail = lead.Email;
                    newAccount.HC_fld_cuentaBancaria__c = lead.HC_fld_cuentaBancaria__c;
                    newAccount.HC_fld_documentoIdentidad__c = lead.HC_fld_documentoIdentidad__c;
                    newAccount.HC_fld_estadoCivil__c = lead.HC_fld_estadoCivil__c;
                    newAccount.HC_fld_frecuenciaPago__c = lead.HC_fld_frecuenciaPago__c;
                    newAccount.HC_fld_identificacionBanco__c = lead.HC_fld_identificacionBanco__c;
                    newAccount.HC_fld_preferenciasComunicacion__c = lead.HC_fld_preferenciasComunicacion__c;
                    newAccount.HC_fld_tipoPago__c = lead.HC_fld_tipoPago__c;
                    //newAccount.PersonBirthdate = lead.HealthCloudGA__BirthDate__c;
                    //newAccount.PersonGenderIdentity = lead.HealthCloudGA__Gender__c;
                    newAccount.ParentId = lead.HealthCloudGA__RelatedAccount__c;
                    //newAccount.OwnerId = lead.OwnerId;
                    newAccount.Phone = lead.Phone;
                    newAccount.ShippingPostalCode = lead.PostalCode;
                    newAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HC_rt_miembroCompania').getRecordTypeId();
                    newAccount.ShippingState = lead.State;
                    newAccount.ShippingStreet = lead.Street;
                    newAccount.Name = lead.FirstName+' '+lead.LastName;
                    insert newAccount;
                    
                    //Creamos los contactos de emergencias relacionados con el usuario
                    Contact newContact = new Contact();
                    newContact.FirstName = lead.HealthCloudGA__EmergencyContactFirstName__c;
                    newContact.LastName = lead.HealthCloudGA__EmergencyContactLastName__c;
                    newContact.Phone = lead.HealthCloudGA__EmergencyContactPhone__c;
                    newContact.AccountId = lead.HealthCloudGA__RelatedAccount__c;
                    newContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('HC_rt_contactmiembroCompania').getRecordTypeId();
                    
                    insert newContact;
                    
                    AccountContactRelation newAccountContactRelation = new AccountContactRelation();
                    newAccountContactRelation.AccountId = newAccount.Id;
                    newAccountContactRelation.ContactId = newContact.Id;
                    newAccountContactRelation.HC_fld_tipoContacto__c = 'Contacto de emergencia';
                    
                    insert newAccountContactRelation;
                    
                    //Creamos El contacto para el usuario de portal user
                    Contact newContactPortal = new Contact();
                    newContactPortal.AccountId = newAccount.Id;
                    newContactPortal.Email = lead.Email;
                    newContactPortal.FirstName = lead.FirstName;
                    newContactPortal.LastName = lead.LastName;
                    newContactPortal.Phone = lead.Phone;
                    newContactPortal.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('HC_rt_portalUser').getRecordTypeId();
                    
                    insert newContactPortal;
                    
                    Id profileId = [Select Id From Profile Where Name = 'Customer Community Plus Login User' LIMIT 1].Id;
                    
                    //Creamos User comunidad
                    User communityUser = new User(FirstName = lead.FirstName, LastName = lead.LastName,
                                                  Email = lead.Email,
                                                  ContactId = newContactPortal.Id,
                                                  ProfileId = profileId, 
                                                  UserName = lead.Email+lead.FirstName,
                                                  Alias = lead.FirstName, 
                                                  TimeZoneSidKey = 'America/New_York',
                                                  LocaleSidKey = 'en_US', 
                                                  EmailEncodingKey = 'ISO-8859-1', 
                                                  LanguageLocaleKey = 'en_US',
                                                  Department = 'Miembro de la Compañía');
                    
                    insert communityUser;
                    
                    List<CareProgramEnrollee> lstCareProgramEnrolle = [select CareProgramId, CareProgram.BudgetAmount, AccountId from CareProgramEnrollee where LeadId = :lead.id ];
                    if(!lstCareProgramEnrolle.isEmpty()){
                        for(CareProgramEnrollee cpe : lstCareProgramEnrolle){
                            cpe.AccountId = newAccount.Id;
                        }
                    }
                    update lstCareProgramEnrolle;
                    
                    List<HealthCondition> lstHcondition = [select PatientId from HealthCondition where HC_fld_lead__c = :lead.id];
                    
                    if(!lstHcondition.isEmpty()){
                        for(HealthCondition hc : lstHcondition){
                            hc.RecordCreatorId = newAccount.Id;
                        }
                    }
                    
                    update lstHcondition;
                    
                    Contract newContrato = new Contract(); 
                    newContrato.AccountId =  newAccount.Id;
                    newContrato.BillingCity =  lead.City;
                    newContrato.BillingCountry =  lead.Country;
                    newContrato.BillingPostalCode =  lead.PostalCode;
                    newContrato.BillingState =  lead.State;
                    newContrato.BillingStreet =  lead.Street;
                    newContrato.CompanySignedId =  lead.OwnerId;
                    newContrato.CompanySignedDate =  Date.today();
                    newContrato.Name =  newAccount.Name;
                    newContrato.StartDate =  Date.Today();
                    newContrato.CustomerSignedId =  newContactPortal.Id;
                    newContrato.Description =  lead.Description;
                    newContrato.Status =  'Activo';
                    newContrato.RecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('HC_rt_contratoSeguroCliente').getRecordTypeId();
                    
                    insert newContrato;
                    
                    ContractGroupPlan newContractGroupPlan = new ContractGroupPlan();
                    newContractGroupPlan.Name = newAccount.Name;  
                    newContractGroupPlan.AccountId = newAccount.Id;  
                    newContractGroupPlan.ContractId = newContrato.Id;           
                    newContractGroupPlan.RecordTypeId = Schema.SObjectType.ContractGroupPlan.getRecordTypeInfosByDeveloperName().get('HC_rt_contratoSeguroCliente').getRecordTypeId();
                    
                    insert newContractGroupPlan;
                    
                    InsurancePolicy newInsurancePolicy = new InsurancePolicy();
                    newInsurancePolicy.RecordTypeId = Schema.SObjectType.InsurancePolicy.getRecordTypeInfosByDeveloperName().get('HC_rt_polizaSeguros').getRecordTypeId();   
                    newInsurancePolicy.ContractGroupPlanId = newContractGroupPlan.id;   
                    newInsurancePolicy.HC_fld_renovacionAutomatica__c = true;   
                    newInsurancePolicy.DateRenewed = date.today().addYears(1);
                    newInsurancePolicy.OwnerId = lead.OwnerId;   
                    newInsurancePolicy.PremiumAmount = lstCareProgramEnrolle[0].CareProgram.BudgetAmount;   
                    newInsurancePolicy.PremiumFrequency = lead.HC_fld_frecuenciaPago__c;   
                    newInsurancePolicy.NameInsuredId = lead.HealthCloudGA__RelatedAccount__c;   
                    newInsurancePolicy.PolicyName = newAccount.Name;   
                    newInsurancePolicy.Name = newAccount.Name;  
                    
                    insert newInsurancePolicy;
                    
                    List<CoverageBenefit> lstCoverageBenefit = [SELECT name, BenefitNotes FROM CoverageBenefit where HC_fld_careProgram__c  = :lstCareProgramEnrolle[0].CareProgramId];
                    
                    List<InsurancePolicyCoverage> lstInsurancePolicyCoverage = new List<InsurancePolicyCoverage>();
                    if(!lstCoverageBenefit.isEmpty()){
                        for( CoverageBenefit cb : lstCoverageBenefit){
                            InsurancePolicyCoverage newInsurancePolicyCoverage = new InsurancePolicyCoverage();
                            newInsurancePolicyCoverage.CoverageName = cb.Name;
                            newInsurancePolicyCoverage.InsurancePolicyId = newInsurancePolicy.ID;
                            newInsurancePolicyCoverage.RecordTypeId = Schema.SObjectType.InsurancePolicyCoverage.getRecordTypeInfosByDeveloperName().get('HC_rt_coverturaPolizaSeguros').getRecordTypeId();   
                            lstInsurancePolicyCoverage.add(newInsurancePolicyCoverage);
                        }
                    }
                    
                    insert lstInsurancePolicyCoverage;
                    
                    List<ContentDocumentLink> lstContentDocumentLink = new List<ContentDocumentLink>();
                    for(ContentDocumentLink cdl : [select LinkedEntityId,ContentDocumentId, Visibility,  ShareType from ContentDocumentLink where LinkedEntityId = :lead.id]){
                        ContentDocumentLink newContentDocumentLink = new ContentDocumentLink();
                        newContentDocumentLink.LinkedEntityId = newContrato.id;
                        newContentDocumentLink.ContentDocumentId = cdl.ContentDocumentId;
                        newContentDocumentLink.Visibility = cdl.Visibility;
                        newContentDocumentLink.ShareType = cdl.ShareType;
                        lstContentDocumentLink.add(newContentDocumentLink);
                    }
                    
                    insert lstContentDocumentLink;
                }
            }
        }
        
    }
    
}