objects/CareProgram.object
<CustomObject>
    <fields>
        <fullName>HC_fld_checkPeriodoCarencia__c</fullName>
        <defaultValue>false</defaultValue>
        <description>¿Con Periodos de Carencia?</description>
        <label>¿Con Periodos de Carencia?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HC_fld_descFormPagoAnual__c</fullName>
        <description>Descuentos por Forma de Pago Anual</description>
        <label>Descuentos por Forma de Pago Anual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>HC_fld_descFormPagoTrimestral__c</fullName>
        <description>Descuentos por Forma de Pago Trimestral</description>
        <label>Descuentos por Forma de Pago Trimestral</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>HC_fld_periodoCarenciaDiagAltaTec__c</fullName>
        <description>Periodo Carencia Diagnóstico de alta tecnología</description>
        <label>Periodo Carencia Diagnóstico de alta tec</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HC_pl_periodoCarencia</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_periodoCarenciaPodologia__c</fullName>
        <description>Periodo Carencia Podología</description>
        <label>Periodo Carencia Podología</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HC_pl_periodoCarencia</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_periodoCarenciaPrepAsistParto__c</fullName>
        <description>Periodo Carencia Preparación y asistencia al parto</description>
        <label>Periodo Carencia Preparación y asistenci</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HC_pl_periodoCarencia</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_periodoCarenciaTratEsp__c</fullName>
        <description>Periodo Carencia Tratamientos especiales</description>
        <label>Periodo Carencia Tratamientos especiales</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HC_pl_periodoCarencia</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_periodoCarenciaTratInfertilidad__c</fullName>
        <description>Periodo Carencia Tratamiento infertilidad</description>
        <label>Periodo Carencia Tratamiento infertilida</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HC_pl_periodoCarencia</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/CoverageBenefit.object
<CustomObject>
    <fields>
        <fullName>HC_fld_careProgram__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo custom relacionado con Care Program</description>
        <label>Care Program</label>
        <referenceTo>CareProgram</referenceTo>
        <relationshipLabel>Coverage Benefits</relationshipLabel>
        <relationshipName>Coverage_Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>HC_fld_cuentaBancaria__c</fullName>
        <description>Código de la cuenta bancaria (IBAN)</description>
        <label>Código de la cuenta bancaria (IBAN)</label>
        <length>24</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HC_fld_documentoIdentidad__c</fullName>
        <description>D.N.I</description>
        <label>D.N.I</label>
        <length>9</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HC_fld_frecuenciaPago__c</fullName>
        <description>Frecuencia de Pago</description>
        <label>Frecuencia de Pago</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mensual</fullName>
                </value>
                <value>
                    <fullName>Trimestral</fullName>
                </value>
                <value>
                    <fullName>Semestral</fullName>
                </value>
                <value>
                    <fullName>Anual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_identificacionBanco__c</fullName>
        <description>Santander(BSCHESMMXXX), BBVA (BBVAESMMXXX), Caixa (CAIXESBBXXX), Sabadell(BSABESBBXXX), Bankinter(BKBKESMMXXX), Unicaja (UCJAES2MXXX)</description>
        <label>Código de identificación del banco (BIC)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Santander(BSCHESMMXXX)</fullName>
                </value>
                <value>
                    <fullName>BBVA (BBVAESMMXXX)</fullName>
                </value>
                <value>
                    <fullName>Caixa (CAIXESBBXXX)</fullName>
                </value>
                <value>
                    <fullName>Sabadell (BSABESBBXXX)</fullName>
                </value>
                <value>
                    <fullName>Bankinter (BKBKESMMXXX)</fullName>
                </value>
                <value>
                    <fullName>Unicaja (UCJAES2MXXX)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HC_fld_tipoPago__c</fullName>
        <description>Tipo de Pago: Orden de Domiciliación o No domiciliada</description>
        <label>Tipo Pago</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Orden de Domiciliación</fullName>
                </value>
                <value>
                    <fullName>No domiciliada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

globalValueSets/HC_pl_periodoCarencia.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>3 meses</fullName>
    </customValue>
    <customValue>
        <fullName>6 meses</fullName>
    </customValue>
    <customValue>
        <fullName>8 meses</fullName>
    </customValue>
    <customValue>
        <fullName>9 meses</fullName>
    </customValue>
    <customValue>
        <fullName>12 meses</fullName>
    </customValue>
    <customValue>
        <fullName>48 meses</fullName>
    </customValue>
    <description>Periodo de Carencia</description>
    <masterLabel>Periodo de Carencia</masterLabel>
</GlobalValueSet>

classes/HC_cls_LeadGenerateContract_cc.cls
/*
@name: HC_cls_LeadGenerateContract_cc
@version: 1.0
@creation date: 20/08/2024
@author: Rocío Vecino Torres
*/
public without sharing class HC_cls_LeadGenerateContract_cc {
    public Lead lead { get; private set; }
    public CareProgramEnrollee  careProgramEnrollee  { get; private set; }
    public String coverturas { get; private set; }
    public Decimal descFormaPago { get; private set; }    
    public String pdfUrl { get; private set; }    
    
    // Constructor del controlador de extensión
    public HC_cls_LeadGenerateContract_cc(ApexPages.StandardController stdController) {
        // Obtén el Lead desde el controlador estándar
        this.lead = (Lead)stdController.getRecord();
        
        // Obtener el ID del Lead desde el controlador estándar
        Id leadId = stdController.getId();
        
        // Realizar la consulta a la base de datos para obtener el Lead
        lead = [SELECT Id, Name, Street, City, PostalCode, Email, HC_fld_documentoIdentidad__c, Phone, HC_fld_frecuenciaPago__c, HC_fld_tipoPago__c, HC_fld_cuentaBancaria__c,HC_fld_identificacionBanco__c
                      FROM Lead 
                      WHERE Id = :leadId 
                      LIMIT 1];
        

        careProgramEnrollee = [select CareProgramId, CareProgram.name, CareProgram.BudgetAmount, CareProgram.Description, CareProgram.HC_fld_descFormPagoAnual__c, CareProgram.HC_fld_descFormPagoTrimestral__c, 
                               CareProgram.HC_fld_periodoCarenciaDiagAltaTec__c, CareProgram.HC_fld_periodoCarenciaPodologia__c, CareProgram.HC_fld_periodoCarenciaPrepAsistParto__c, 
                               CareProgram.HC_fld_periodoCarenciaTratEsp__c, CareProgram.HC_fld_periodoCarenciaTratInfertilidad__c, CareProgram.HC_fld_checkPeriodoCarencia__c 
                               FROM CareProgramEnrollee where  LeadId = :leadId LIMIT 1];
        
        if(lead.HC_fld_frecuenciaPago__c == 'Trimestral'){
            descFormaPago = careProgramEnrollee.CareProgram.HC_fld_descFormPagoTrimestral__c;
        }else if(lead.HC_fld_frecuenciaPago__c == 'Anual'){
            descFormaPago = careProgramEnrollee.CareProgram.HC_fld_descFormPagoAnual__c;
        }else{
            descFormaPago = 0;
        }
        
        for(CoverageBenefit cov : [select name from CoverageBenefit where HC_fld_careProgram__c = :careProgramEnrollee.CareProgramId]){
            if(String.isBlank(coverturas)){
                coverturas = cov.name;
            }else{
                coverturas = coverturas+'; '+cov.name;
            }
        }
    }
    // Método para generar el PDF
    public PageReference generateAndSavePdf() {
        // Generar el PDF
        PageReference pdfPage = Page.HC_vf_generarContrato;
        pdfPage.getParameters().put('id', lead.Id);
        Blob pdfBlob;
        try {
            pdfBlob = pdfPage.getContent();
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error al generar el PDF: ' + e.getMessage()));
            return null;
        }

        // Guardar el PDF como un Attachment
        Attachment attachment = new Attachment();
        attachment.ParentId = lead.Id;
        attachment.Name = 'Contrato_Salud_' + lead.Name + '.pdf';
        attachment.Body = pdfBlob;
        attachment.ContentType = 'application/pdf';
        insert attachment;

        // Actualizar el URL del PDF
        pdfUrl = '/' + attachment.Id;
        
        return null;
    }
}